---

substitutions:
  _SLACK_WEBHOOK: 'key'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/exercises-php:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/exercises-php:latest',
      '.'
    ]
  - name: 'docker/compose:1.15.0'
    args: [
      'up',
    ]

  - name: 'technosophos/slack-notify'
    env:
      - 'SLACK_WEBHOOK=${_SLACK_WEBHOOK}'
      - 'SLACK_MESSAGE=Nginx was built (${SHORT_SHA})'
      - 'SLACK_TITLE="${PROJECT_ID}:${BRANCH_NAME}"'
      - 'SLACK_USERNAME=cloudbuild'

images: ['gcr.io/$PROJECT_ID/exercises-php:latest']

